
import './globals.css'
import Navbar from '@/components/views/Navbar'
import { Sora } from 'next/font/google'
import Wrapper from '@/components/shared/Wrapper'
import Footer from '@/components/views/Footer'


const inter = Sora({ subsets: ['latin'],
weight:["100","200","300","400","500","600"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <Navbar/>
        
        <div className='min-h-screen'>{children}</div>
        <Footer/>
        </Wrapper>
        </body>
    </html>
  )
}
